module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
    fontSize: {
      "1vw": "1vw",
      "1.5vw": "1.5vw",
      "2vw": "2vw",
      "2.5vw": "2.5vw",
      "3vw": "3vw",
      "3.5vw": "3.5vw",
      "4vw": "4vw",
      "4.5vw": "4.5vw",
      "5vw": "5vw",
      "5.5vw": "5.5vw",
      "6vw": "6vw",
      "6.5vw": "6.5vw",
      "7vw": "7vw",
      "7.5vw": "7.5vw",
      "8vw": "8vw",
      "8.5vw": "8.5vw",
      "9vw": "9vw",
      "9.5vw": "9.5vw",
      "10vw": "10vw",
    },
  },
  plugins: [],
}
